### ISSUE TITLE
Add comma separation to community pledge

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/taho.xyz#108]
before thousands place

"103501" --> "103,501"

<img width="1185" alt="Screen Shot 2022-09-26 at 11 11 50 AM" src="https://user-images.githubusercontent.com/7005061/192313982-52c4c0c0-d5f5-4654-830a-80ee37371d32.png">

<img width="1334" alt="Screen Shot 2022-09-26 at 11 11 46 AM" src="https://user-images.githubusercontent.com/7005061/192313984-a1e522f1-2793-42be-a5e4-19d6671c6b43.png">

**Comment by VladUXUI** [comment]
Maybe we can put both of these in same PR https://github.com/tallycash/tally.cash/issues/108
