### ISSUE TITLE
Update taho.xyz greenhouse link

### ISSUE THREAD

**Issue by Naxsun** [tahowallet/taho.xyz#168]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Greenhouse was updated because of the rename

### What did not work?

Required updated: 
https://boards.greenhouse.io/tallywallet/ 

to 

https://boards.greenhouse.io/tahowallet

<img width="1133" alt="Screen Shot 2023-04-03 at 20 15 19" src="https://user-images.githubusercontent.com/71384922/229593040-13d27c65-31c9-46fe-96bc-b9c389cd5f1d.png">

### Version

v0.28.1

**Comment by jagodarybacka** [comment]
ah, you created issue here as well, closing as duplicate then 😉

**Comment by Naxsun** [comment]
Ah I intended to close it, sorry for that!
