### ISSUE TITLE
10/24 website updates

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/taho.xyz#176]
https://taho.xyz/security

1/ Update banner: "The Subscape Beta is launching soon! [Join the waitlist.](https://waitlist.taho.xyz/)" 

![image](https://github.com/tahowallet/taho.xyz/assets/7005061/a91870be-f1cf-43f4-8b04-84cd2fa05a12)

2/ drop "web3 pledge" from top nav

3/ "View all your Ethereum, Polygon, Optimism and Arbitrum NFTs." --> "View all your NFTs in one place."

4/ "Supported by the biggest projects in web3." -> Let's remove Rook and Saddle since they are inactive

++++

https://taho.xyz/security

1/ Add our most recent audit

Least Authority	July 20223	Private Key Import + Recovery Phrase Reveal [link]( https://leastauthority.com/blog/audits/audit-of-taho-wallet/?ref=blog.taho.xyz
)

**Comment by jagodarybacka** [comment]
Done https://github.com/tahowallet/taho.xyz/pull/177
